### ISSUE TITLE
Static IP pvoutput.org changed

### ISSUE THREAD

**Issue by ghost** [joeyloman/esp8266-pvoutput-logger#1]
Hi,

First of all, thank you for your great work.

I've build this project but didn't get it to work. It's been running for 3 days and nothing was uploaded to pvoutput.org 
Long story short: the IP has changed to 45.56.66.169

I changed it in my local source and now it's working.
Please either make it dynamic, or change th ip in your source code.

Regards from Germany.

**Comment by joeyloman** [comment]
Hi @HermanusF,

Sorry for the response delay on this issue. Great to hear that you are using the software.

The static ip stuff isn't used. If you look at the pvoutput_client.c you will see the PVOUTPUT_WEBSERVER_IP variable, but it's commented out later in the code. The PVOUTPUT_WEBSERVER_HOSTNAME (which points to the pvoutput.org hostname) is used in this case so it's already dynamic :-)

Kind regards,

Joey

**Comment by ghost** [comment]
Hi Joey,

I don't think you're right because it started working since I changed the IP, and only the IP.
I am not able to look into it at the moment, but when I do I'll let you know.

Thanks for your answer.
